dist: trusty
language: node_js
node_js:
  - 'lts/*'
  - '8'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false

before_install:

before_script:
  - npm prune
script:
  - npm run build:all
  - npm run cover
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release
